### ISSUE TITLE
Highlight differences between other similar libraries

### ISSUE THREAD

**Issue by jlevycpa** [swoosh/swoosh#107]
Hello,

It looks like this library was started after Bamboo was already established. It would be helpful to have a section in the README addressing how this library differs from Bamboo, and why it was necessary to create a separate project. For example, is there a fundamental design objective or approach which differs between the projects? This will make it easier for consuming developers to decide which is right for them.

Thank you!

**Comment by princemaple** [comment]
@stevedomin care to put in a few words?

I personally find them very, very similar. I discovered Bamboo first but switched to Swoosh for some reason that I can't recall anymore...

**Comment by stevedomin** [comment]
The train has probably left the station already on this one, but I still want to provide a response before closing it.

@jlevycpa The design of the two libraries is indeed very similar but has roots in the Elixir ecosystem more than anything (adapters from Ecto, etc.). I started Swoosh, and then realised Bamboo existed so I started contributing to it. Because I had already started working on my own email library I had some reckons about the design, nothing major, but couldn't agree with Paul at the time so I decided to keep working on my own. I thought some "competition" would be beneficial for the Elixir ecosystem.

With hindsight I'm not sure it was the best decision, maintaining an open-source library is difficult and I'm not as reactive and proactive about improving it as I'd want to be (this issue is a perfect illustration of that fact 😄).

To answer your question, no, there is no fundamental difference between the two. Although I haven't looked at Bamboo for a while so there might be by now.
