### ISSUE TITLE
Provide a `deliver_later` function

### ISSUE THREAD

**Issue by maxcell** [swoosh/swoosh#136]
Curious on the reasoning for not having a potential way to deliver mail asynchronously? I looked for it in the issues but couldn't find anything. Is this an idea to add or would this restrict the logic too much for another user?

**Comment by princemaple** [comment]
Hi Maxcell,

Concurrency is so very first class in Elixir and it is as easy as `Task.start(MyEmailModule, :send_welcome_email, [arg1, arg2])` to asynchronously send an email. Many libs of different uses provide their async strategy, which can be useful, but it can often be very repetitive and useless to have a built in way of "doing it asynchronously" in Elixir libs if you already have developed a universal / business-specific way of doing it. That is my thought. I'm not sure if @stevedomin ever thought about adding an builtin approach to it.

Additionally, email-sending functionality can be very business logic oriented. Do you want to retry? How do you want to handle async errors? Those are the questions that you may get different answers from different users of the lib. It's hard to satisfy every user.

Po

**Comment by stevedomin** [comment]
hello @maxcell, very good question!

As @princemaple said it would be very easy to start using `Task` to send emails in your project. The reason why this convenience was deliberately not added to this project is that I want users to make the decision about the tradeoffs involved with doing it this way.

Many people coming to Elixir, Phoenix and presumably Swoosh come from the Rails world and the `deliver_later` function has a special semantic attached to it, it usually means that the email delivery will be done using ActiveJob to provide asynchronous execution. That also means you can easily see if it has failed, it can be retried, etc.

It wouldn't be the case with `Task`, or at least not with a naive `Task` implementation, and that's why I've been reluctant to add it to Swoosh.

However it would probably be worth adding a section to the README and the docs explaining this reasoning.

I'm also very open to revisiting this question, at least maybe we can add a Behaviour that would have to be implemented by various backends to provide the `deliver_later` functionality. What do you think?

**Comment by princemaple** [comment]
Now we have a section in README about async! https://github.com/swoosh/swoosh#async-emails

**Comment by maxcell** [comment]
Thank you by the way @princemaple ❤️ I really do appreciate this a lot.

**Comment by princemaple** [comment]
@maxcell not a problem at all :)
