### ISSUE TITLE
Can't find Jason in Production

### ISSUE THREAD

**Issue by zmcNotafraid** [swoosh/swoosh#242]
After update 1.14, local is ok to run swoosh.But in production mode cause  Jason encode error.It's there any operation need us to do ?

**Comment by princemaple** [comment]
could you show the full error message?

**Comment by zmcNotafraid** [comment]
Just now we fix it. We use swoosh in Coherence deps, not add it in mix.exs standalone. But seem it didn't include Jason.So we add Jason in mix.exs.And It's work.

**Comment by princemaple** [comment]
thanks for the update

**Comment by denispeplin** [comment]
@zmcNotafraid, same trouble. Have you add it into `applications` list?

**Comment by costaraphael** [comment]
So, I was taking a look at the code, there is no fallback to Poison when looking up the `:json_library` configuration.

This broke our email delivery as well, so I had to add the configuration to use Poison.

IMO, one of two things should happen:
- Implement a proper fallback to `Poison` in the `Swoosh.json_library/0` function;
- Document that there is a breaking change and that the user should either add `Jason` to his deps or setup the `:json_library` config.

I prefer the first one, because nobody expects a breaking change in a minor version bump.

If you want me to tackle it I can come up with a PR.

**Comment by princemaple** [comment]
Hi, Swoosh has Jason as its explicit required dependency. If you ran `mix
deps.update` to update Swoosh from an older version to a newer version, it
should pull in Jason with no trouble at all. The probable scenario here is,
you have a very simple deployment setup that simply throws code onto a
server. If you had a `mix deps.get` somewhere in the deployment
script/command/anything, it should not be a problem. Honestly, people only
think it's swoosh's fault because we took the first bullet. If you had any
other lib that changes its dependency, you are most likely to encounter the
same problem. The real problem to solve is the deployment setup.

**Comment by princemaple** [comment]
Thanks a lot for the investigation. You are right about the application listing. Since we require elixir 1.4

**Comment by princemaple** [comment]
@costaraphael no worries. Thank you for the detailed breakdown!
