### ISSUE TITLE
Logo design

### ISSUE THREAD

**Issue by Batarian711** [swoosh/swoosh#273]
Hi. I am a graphic designer. I like helping open-source projects. I want to give you a logo to use in the readme file. Do you have an idea? What do you say?

**Comment by princemaple** [comment]
Haha @stevedomin

**Comment by Batarian711** [comment]
Is there a problem ?

**Comment by princemaple** [comment]
No, I just don't have an opinion. :)

**Comment by Batarian711** [comment]
Do you want me to do ?

**Comment by princemaple** [comment]
I want Steve to see it first :)

**Comment by stevedomin** [comment]
@Batarian711 since you asked the same thing in https://github.com/duffelhq/paginator but I didn't have  time to reply, here's my take on it:

I can't think of anyone who wouldn't be happy to get a free logo for their open source project, however everyone will want a good quality one. Right now, it's hard to assess whether that will be the case. You say that you like helping open source projects, why not send links to logos you have already done? Or a link to a portfolio? If you don't have one, I'd recommend shooting in the dark and sending a proposition when submitting the issue. People may not like it but at least you can show some things you've done.

So, why not, but I'd like to see some of the stuff you've done first!
