### ISSUE TITLE
ElasticEmail -- or switch?

### ISSUE THREAD

**Issue by sensiblearts** [swoosh/swoosh#384]
Hi,
I already have an ElasticEmail account for another project, and need to choose:
- use Swoosh and write an adapter?
- use Bamboo and [bamboo_elastic_email](https://github.com/KineticCafe/bamboo_elastic_email) ?
- use Swoosh and get e.g., SendGrid account

Any strong opinions?

I had some delivery issues with ElasticEmail, but I think it was my settings on my SPF and DKIM, and/or cert or IP issues. Confusing stuff.

Thanks,
David

**Comment by princemaple** [comment]
Hi David,

Frankly, it's entirely up to you and is mostly by preference. My usual setup is swoosh+sparkpost. I haven't been following bamboo since quite long ago, so I can't list a comparison list or pros and cons. Most bamboo are third party libs, making it harder to track. They are very much alike anyways.

Regards,
Po
