### ISSUE TITLE
sslv3 issue in production

### ISSUE THREAD

**Issue by IlyasM** [swoosh/swoosh#478]
Hi, everything works fine locally, but when I run on remote host in production I get the following:

{:error,
 {:options, {:sslv3, {:versions, [:"tlsv1.2", :"tlsv1.1", :tlsv1, :sslv3]}}}}

How to fix this?

**Comment by princemaple** [comment]
Which provider? Are you on OTP23?

**Comment by IlyasM** [comment]
Yes otp 23, elixir compiled on 21

**Comment by princemaple** [comment]
This could be caused by your provider not doing their job, or OTP 23 removing old SSL encryption options. Try passing `[ssl_options: [versions: [:"tlsv1.2"]]]` as `hackney_options` in `%Email{}`'s private field.

```elixir
# somewhere in your pipeline that constructs the email
|> put_private(:hackney_options, [ssl_options: [versions: [:"tlsv1.2"]]])`
```

If this doesn't work, you probably have to remind your provider to upgrade their infrastructure... Not very likely though, the OTP issue is a lot more likely and I've had it before.

**Comment by IlyasM** [comment]
Thank you very much. This solved it.

**Comment by princemaple** [comment]
Thanks for the confirmation!
