### ISSUE TITLE
Swoosh.Adapters.Test is not working with Wallaby

### ISSUE THREAD

**Issue by rafa-dyad** [swoosh/swoosh#662]
Hi!
I'm struggling to get Swoosh.Adapters.Test to work on our project. The most important thing about my test I can think of is that it is triggering the mailer via a web request run by wallaby. The code is working ok, the mailer is working, and I verified that the test adapter is correctly setup by modifying its code and adding an inspect call to the deliver function. 

So I know the test adapter is being called correctly, but assert_email_sent fails no matter what.

` feature "password reset", %{session: session} do
    user = Users.get_user_by_email("user@mail.com")

    session
    |> visit("/")
    |> click(link("FORGOT PASSWORD"))
   ...
 
    assert_email_sent()`

Any ideas? Thank you

**Comment by princemaple** [comment]
Hi, `Swoosh.TestAssertion` works for unit tests and basic integration tests. Unfortunately it's not going to work for feature/E2E tests. The mechanism of `assert_email_sent` is based on messaging sending between processes, and is expecting the calling process (the one that calls `assert_email_sent`) to be the calling process of `Mailer.deliver`, or be the parent process of the whatever does the `Mailer.deliver` call.

For feature/E2E tests, you should use the local adapter. In your test, instead of calling `assert_email_sent`, you should navigate to the preview url and use `wallaby` to make sure the email is in the inbox.

**Comment by rafa-dyad** [comment]
Thank you @princemaple, I was able to set a working test, much appreciated.

I'd like to suggest including this advice in the docs for Swoosh.TestAssertion

**Comment by princemaple** [comment]
Good suggestion. Thanks 👍
