### ISSUE TITLE
Missing documentation of deliver!/2

### ISSUE THREAD

**Issue by krns** [swoosh/swoosh#939]
### Describe the bug

- [`deliver!/2`](https://github.com/swoosh/swoosh/blob/v1.16.10/lib/swoosh/mailer.ex#L132) is not documented
- only `deliver/2` is [documented](https://hexdocs.pm/swoosh/Swoosh.Mailer.html#deliver/2)

### Steps to Reproduce the Bug or Issue

See the latest docs: https://hexdocs.pm/swoosh/Swoosh.Mailer.html#deliver/2

**Comment by ivanhercaz** [comment]
Hi! I opened a PR with brief documentation for the functions of the `__using__` macro in the `Swoosh.Mailer` module. However, @krns, take into account that `deliver!/2`  won't be documented in the `Swoosh.Mailer` docs because it is only defined inside the `__using__` macro. The documentation of these functions is available when another project/package/whatever makes use of `use Swoosh.Mailer` and, there, the `deliver!/2` will have docs. And if the developer generates the docs for that project, in the module in which `use Swoosh.Mailer` is implemented, the docs will show the documentation for these functions (as the example I attached below).

![image](https://github.com/user-attachments/assets/81e42b53-6e95-418f-88c9-d16809ebfa0f)
